"use client";
import { useMemo, useState } from "react";
import { analyticsSnapshot, monthAnalytics, weekAnalytics } from "@/domain/analytics";
import { dateRange } from "@/domain/periods";
import { useLedger } from "./ledger-provider";
import { dollars, today } from "./display";
type Mode = "month" | "week" | "custom";
function BarChart({ title, items, total }: { title: string; items: { label: string; amountMinor: number }[]; total: number }) { return <section className="panel chart" aria-label={title}><h3>{title}</h3>{!items.length ? <p className="muted">Нет расходов в выбранном периоде.</p> : <div className="bars">{items.map(item => <div className="bar-row" key={item.label}><span>{item.label}</span><div className="bar-track"><div className="bar-fill" style={{ width: `${total ? Math.max(3, item.amountMinor / total * 100) : 0}%` }} /></div><strong>{dollars(item.amountMinor)}</strong></div>)}</div>}</section>; }
export function DashboardScreen() {
  const { ledger } = useLedger(); const [mode, setMode] = useState<Mode>("month"); const [month, setMonth] = useState(() => today().slice(0, 7)); const [weekDate, setWeekDate] = useState(() => today()); const [start, setStart] = useState(() => `${today().slice(0, 7)}-01`); const [end, setEnd] = useState(() => today()); const [categoryId, setCategoryId] = useState("all");
  const snapshot = useMemo(() => { if (!ledger) return null; try { if (mode === "month") return monthAnalytics(ledger, month, categoryId); if (mode === "week") return weekAnalytics(ledger, weekDate, categoryId); return analyticsSnapshot(ledger, dateRange(start, end), categoryId); } catch { return null; } }, [ledger, mode, month, weekDate, start, end, categoryId]);
  if (!ledger) return null;
  const selectedCategory = ledger.categories.find(row => row.id === categoryId);
  return <><h2>Dashboard</h2><p className="muted">Доходы, расходы и бюджет за выбранный период.</p>
    <section className="panel filters" aria-label="Фильтры отчёта"><h3>Период и категория</h3><div className="filter-tabs" role="group" aria-label="Тип периода">{([["month", "Месяц"], ["week", "Неделя"], ["custom", "Диапазон"]] as const).map(([value, label]) => <button key={value} type="button" className={mode === value ? "primary" : ""} aria-pressed={mode === value} onClick={() => setMode(value)}>{label}</button>)}</div>{mode === "month" && <label htmlFor="report-month">Месяц<input id="report-month" type="month" value={month} onChange={e => setMonth(e.target.value)} /></label>}{mode === "week" && <label htmlFor="report-week">Дата недели<input id="report-week" type="date" value={weekDate} onChange={e => setWeekDate(e.target.value)} /></label>}{mode === "custom" && <div className="form-grid"><label htmlFor="report-start">С даты<input id="report-start" type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label htmlFor="report-end">По дату<input id="report-end" type="date" value={end} onChange={e => setEnd(e.target.value)} /></label></div>}<label htmlFor="report-category">Категория расходов<select id="report-category" value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="all">Все категории</option>{ledger.categories.map(row => <option key={row.id} value={row.id}>{row.name}{row.archived ? " (архив)" : ""}</option>)}</select></label>{selectedCategory?.archived && <p className="muted">Архивная категория включена, потому что она есть в истории.</p>}</section>
    {!snapshot ? <p role="alert" className="field-error">Проверьте выбранный период.</p> : <><p className="muted" aria-label="Выбранный период">Период: {snapshot.period.start} — {snapshot.period.end}</p><section className="kpi-grid" aria-label="Итоги периода"><article className="kpi"><span>Доходы</span><strong className="income">{dollars(snapshot.incomeMinor)}</strong></article><article className="kpi"><span>Расходы{categoryId !== "all" ? ` · ${selectedCategory?.name ?? "категория"}` : ""}</span><strong className="expense">{dollars(snapshot.expenseMinor)}</strong></article><article className="kpi"><span>Доход − расход</span><strong className={snapshot.balanceMinor < 0 ? "expense" : "income"}>{snapshot.balanceMinor < 0 ? "−" : ""}{dollars(Math.abs(snapshot.balanceMinor))}</strong></article><article className="kpi"><span>Бюджет</span><strong>{snapshot.budgetMinor === null ? "Не задан" : dollars(snapshot.budgetMinor)}</strong><small>{snapshot.remainingBudgetMinor === null ? "Для периода нет бюджета" : `Остаток: ${snapshot.remainingBudgetMinor < 0 ? "−" : ""}${dollars(Math.abs(snapshot.remainingBudgetMinor))}`}</small></article></section><div className="dashboard-grid"><BarChart title="Расходы по категориям" total={snapshot.expenseMinor} items={snapshot.categoryTotals.map(row => ({ label: `${row.name}${row.archived ? " (архив)" : ""}`, amountMinor: row.amountMinor }))} /><BarChart title="Основные показатели" total={Math.max(snapshot.incomeMinor, snapshot.expenseMinor, 1)} items={[{ label: "Доходы", amountMinor: snapshot.incomeMinor }, { label: "Расходы", amountMinor: snapshot.expenseMinor }]} /></div></>}
  </>;
}
